### ISSUE TITLE
symlinks is very.... sad

### ISSUE THREAD

**Issue by soredake** [sayeed99/x86_64-GCC-6.1.0-android-toolchain#1]
https://github.com/sayeed99/x86_64-GCC-6.1.0-android-toolchain/blob/master/bin/x86_64-linux-android-strings
`
/home/cyborg/zenfone/tool6/bin/x86_64-linux-android-x86_64-linux-gnu-strings
`

**Comment by sayeed99** [comment]
well yes I know, I need to clean it up :P 
was trying the Google's way to make it and ended up with this, will clean it up in a day or two :) 
will close it as soon as my new work is up :)
